export const USER_LOADED = 'APP_USER_LOADED'
export const USER_UPDATED = 'APP_USER_UPDATED'

export const CHURCHES_LOADED = 'APP_CHURCHES_LOADED'
export const CHURCH_ADMINISTRATORS_LOADED = 'APP_CHURCH_ADMINISTRATORS_LOADED'
export const CHURCH_DONATORS_LOADED = 'APP_CHURCH_DONATORS_LOADED'
export const CHURCH_DONATIONS_LOADED = 'APP_CHURCH_DONATIONS_LOADED'
export const CHURCH_CREATED = 'APP_CHURCH_CREATED'
export const CHURCH_UPDATED = 'APP_CHURCH_UPDATED'
export const CHURCH_ADDED = 'APP_CHURCH_ADDED'
export const CHURCH_DELETED = 'APP_CHURCH_DELETED'
export const CHURCH_REPORT_LOADED = 'APP_CHURCH_REPORT_LOADED'
export const DONATION_STATEMENT_REPORT_LOADED = 'APP_DONATION_STATEMENT_REPORT_LOADED'

export const ADMINISTRATOR_SELECT_CHURCH = 'APP_ADMINISTRATOR_SELECT_CHURCH'
export const ADMINISTRATOR_UPDATED = 'APP_ADMINISTRATOR_UPDATED'
export const ADMINISTRATOR_DELETED = 'APP_ADMINISTRATOR_DELETED'

export const DONATION_CREATED = 'APP_DONATION_CREATED'
export const DONATION_UPDATED = 'APP_DONATION_UPDATED'

export const DONATOR_CREATED = 'APP_DONATOR_CREATED'
export const DONATOR_UPDATED = 'APP_DONATOR_UPDATED'
export const DONATOR_DELETED = 'APP_DONATOR_DELETED'

export const ERROR = 'APP_ERROR'
export const CLEAR_ERROR = 'APP_CLEAR_ERROR'